export const data = [{ 
    selectedProduct:{
      logo: "https://turbologo.com/articles/wp-content/uploads/2019/07/Three-Bars-adidas-logo-1.jpg.webp",
      description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      category: "Men",
      rate: 4.5,
      nomOfRates:"22",
      price:"9,999",
      salePrice: 8999,
      salePercent:"30",
      size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
      color: ['Black', 'White'],
      img: [
            'https://api.yeshtery.com/v1/yeshtery/files/31/hb6547-1-apparel-photography-front-view-white-b3080ed19f19421385c03601cf35d828.jpg?height=150',
            'https://api.yeshtery.com/v1/yeshtery/files/31/hb6547-5-apparel-on-model-back-view-white-165408fb2cb7484d91b09f10c3c2b5ac.jpg?height=500',
            'https://api.yeshtery.com/v1/yeshtery/files/31/hb6547-8-apparel-on-model-detail-view-2-white-0cde1da9c2284e6b83d13a7fff23f593.jpg?height=500',
            'https://api.yeshtery.com/v1/yeshtery/files/31/hb6547-3-apparel-on-model-standard-view-white-691a6fcebdf8402d9d91c44019158c92.jpg?height=500',
            'https://api.yeshtery.com/v1/yeshtery/files/31/hb6547-7-apparel-on-model-detail-view-1-white-13db14e47f2f4215970a29b07d44b874.jpg?height=500',
            'https://api.yeshtery.com/v1/yeshtery/files/31/hb6547-1-apparel-photography-front-view-white-b3080ed19f19421385c03601cf35d828.jpg?height=500',
          ]
      },
      similarProducts: [{
          logo: "https://turbologo.com/articles/wp-content/uploads/2019/07/Three-Bars-adidas-logo-1.jpg.webp",
          description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
          category: "Men",
          rate: 3.5,
          nomOfRates:"22",
          price:"9,999",
          salePrice:"8,999",
          salePercent:"30",
          size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
          color: ['Black', 'white'],
          img: 'https://knoww.cc/wp-content/uploads/2019/07/10405.jpg',
          location: 'Pickup From Mall of Arab'
      },
      {
          logo: "https://turbologo.com/articles/wp-content/uploads/2019/07/Three-Bars-adidas-logo-1.jpg.webp",
          description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
          category: "Men",
          rate: 4,
          nomOfRates:"22",
          price:"9,999",
          salePrice:"8,999",
          salePercent:"30",
          size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
          color: ['Black', 'white'],
          img: 'https://7loo.net/wp-content/uploads/2019/08/2654-11.jpg',
          location: 'Pickup From Mall of Egypt'
      },
      {
          logo: "https://turbologo.com/articles/wp-content/uploads/2019/07/Three-Bars-adidas-logo-1.jpg.webp",
          description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
          category: "Men",
          rate: 5,
          nomOfRates:"12",
          price:"9,699",
          salePrice:"8,899",
          salePercent:"50",
          size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
          color: ['Black', 'white'],
          img: 'https://i.pinimg.com/736x/e9/66/77/e9667798dcaa2d34130c4c40e6f9bb65--adidas-clothes-adidas-mens-clothing.jpg',
          location: 'Pickup From Mall of Egypt'
      },
      {   
          logo: "https://turbologo.com/articles/wp-content/uploads/2019/07/Three-Bars-adidas-logo-1.jpg.webp",
          description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
          category: "Men",
          rate: 2.5,
          nomOfRates:"22",
          price:"9,999",
          salePrice:"8,999",
          salePercent:"30",
          size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
          color: ['Black', 'white'],
          img: 'https://eyess.cc/wp-content/uploads/2019/08/1815-8.jpg',
          location: 'Pickup From Mall of Egypt'
      }]
  }];